ALTER TABLE "cash_closures"
ADD COLUMN "cashSalesTotal" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN "cardSalesTotal" DECIMAL(10,2) NOT NULL DEFAULT 0.00,
ADD COLUMN "vatTotal" DECIMAL(10,2) NOT NULL DEFAULT 0.00;
